cc_binary(
    name = 'plsa',
    srcs = [
        'plsa_test.cpp',
        'plsa.cpp'
    ],
    incs = ['../../ThirdParty/gflags/include/'],
    deps = ['//ML/Common:common',
            '//ThirdParty/gflags/lib:gflags'
           ],
)
