cc_binary(
    name = 'ftrl',
    srcs = [
        'FTRL_test.cpp',
        'FTRL.cpp'
    ],
    incs = ['../../ThirdParty/gflags/include/'],
    deps = ['//ML/Common:common',
            '//ThirdParty/gflags/lib:gflags'
           ],
)
