cc_binary(
    name = 'fm',
    srcs = [
        'fm_main.cpp',
        'inc_fm.cpp'
    ],
    incs = ['../../ThirdParty/gflags/include/'],
    deps = ['//ML/Common:common',
            '//ThirdParty/gflags/lib:gflags'
           ],
)
