cc_binary(
    name = 'load_data',
    srcs = [
        'data_test.cpp',
        'data.cpp'
    ],
    incs = ['../../ThirdParty/gflags/include/',
           '../'],
    deps = ['//ML/Common:common',
            '//ThirdParty/gflags/lib:gflags'
           ],
)
