cc_library(
    name = 'common',
    srcs = [
        'string_util.cpp',
        'log.cpp',
        'thread.cpp',
        'lock.cpp',
    ],
    deps = [
    	'#pthread'
    ],
    optimize = ['O3']
)
